name: pikpik
description: My entry for GitHub's Game Off 2022.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bonfire: ^2.11.6
  flame_audio: ^1.3.3
  flame_splash_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/corn/
    - assets/images/decoration/
    - assets/images/effects/
    - assets/images/enemy/
    - assets/images/enemy/aunt/
    - assets/images/enemy/grandma/
    - assets/images/enemy/grandpa/
    - assets/images/npc/
    - assets/images/player/
    - assets/images/tiles/
    - assets/images/tiled/
    - assets/audio/

  fonts:
    - family: Titan
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
